#系统配置
server:
  port: 8088
  servlet:
    context-path: /

spring:
  #rabbitMQ
  rabbitmq:
    host: 139.196.202.206
    port: 5672
    username: guest
    password: guest
  #redis配置
  redis:
    database: 1
    host: 139.196.202.206
    port: 6379
  #aop
  aop:
    auto: true
    proxy-target-class: true #cglib代理
  #数据源
  datasource:
    type: com.p6spy.engine.spy.P6DataSource
    username: root  #改
    password: root #改
#     开启p6spy对sql进行监控，生产环境建议关闭，有性能损耗
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/internship_system?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/internship_system?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8


    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    ### 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.scau.internshipsystem.system.entity
  configuration:
    map-underscore-to-camel-case: true